name: Build and Test Task1

on:
  push:
    branches: [ main ]
    paths:
      - 'Task1/**'  # Uruchomi workflow tylko dla zmian w folderze Task1
  pull_request:
    branches: [ main ]
    paths:
      - 'Task1/**'  # Uruchomi workflow tylko dla zmian w folderze Task1
  workflow_dispatch:  # Manualne uruchomienie workflow

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Określenie systemów operacyjnych
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y cmake g++
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install cmake
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install cmake
          fi

      - name: Create build directory for Task1
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mkdir Task1\\build
          else
            mkdir -p Task1/build
          fi

      - name: Run CMake for Task1
        run: cmake -S Task1 -B Task1/build/

      - name: Build the project for Task1
        run: cmake --build Task1/build/

      - name: Run tests for Task1
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            Task1\\build\\Task1-ut.exe
          else
            ./Task1/build/Task1-ut
          fi

