name: Build and Test Task1

on:
  push:
    branches: [ main ]
    paths:
      - 'Task1/**'  # Uruchomi workflow tylko dla zmian w folderze task1
  pull_request:
    branches: [ main ]
    paths:
      - 'Task1/**'  # Uruchomi workflow tylko dla zmian w folderze task1
  workflow_dispatch:  # Manualne uruchomienie workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Create build directory for task1
      run: mkdir -p build/task1

    - name: Run CMake for task1
      run: cmake -S task1 -B build/Task1

    - name: Build the project for Task1
      run: cmake --build build/Task1

    - name: Run tests for Task1
      run: ./build/Task1/Tests
