name: Build and Test Task2

on:
  push:
    branches: [ main ]
    paths:
      - 'Task2/**'  # Uruchomi workflow tylko dla zmian w folderze Task2
  pull_request:
    branches: [ main ]
    paths:
      - 'Task2/**'  # Uruchomi workflow tylko dla zmian w folderze Task2
  workflow_dispatch:  # Manualne uruchomienie workflow

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Określenie systemów operacyjnych
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y cmake g++
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install cmake
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install cmake
          fi
        shell: bash

      - name: Create build directory for Task2
        run: mkdir -p Task2/build
        shell: bash

      - name: Run CMake for Task2
        run: cmake -S Task2 -B Task2/build/

      - name: Build the project for Task2
        run: cmake --build Task2/build/

      - name: Run tests for Task2
        run: ./Task2/build/Task2-ut
        shell: bash

