name: Build and Run C++ with CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Create build directory
      run: mkdir -p build

    - name: Run CMake
      run: cmake -S . -B build

    - name: Build the project
      run: cmake --build build

    - name: Run the binary
      run: ./build/Tests
