name: Build and Test Task1

on:
  push:
    branches: [ main ]
    paths:
      - 'Task1/**'  # Uruchomi workflow tylko dla zmian w folderze Task1
  pull_request:
    branches: [ main ]
    paths:
      - 'Task1/**'  # Uruchomi workflow tylko dla zmian w folderze Task1
  workflow_dispatch:  # Manualne uruchomienie workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Create build directory for Task1
      run: mkdir -p Task1/build/

    - name: Run CMake for Task1
      run: cmake -S Task1 -B Task1/build/

    - name: Build the project for Task1
      run: cmake --build Task1/build/

    - name: Run tests for Task1
      run: ./Task1/build/tests-ut
